CREATE TABLE IF NOT EXISTS stg_ods_match_events (
    id SERIAL,
    match_id VARCHAR(50),
    competition_id VARCHAR(50) DEFAULT NULL,
    season_id VARCHAR(50) DEFAULT NULL,
    team_name VARCHAR(100),
    player_name VARCHAR(100),
    player_id VARCHAR(50),
    jersey_number INTEGER,
    pass_recipient_name VARCHAR(100),
    type_name VARCHAR(100),
    sub_type_name VARCHAR(50),
    outcome_name VARCHAR(50),
    pass_cross BOOLEAN,
    player_pattern_name VARCHAR(50),
    card_type VARCHAR(50),
    x NUMERIC(5, 1),
    y NUMERIC(5, 1),
    end_x NUMERIC(5, 1),
    end_y NUMERIC(5, 1),
    zone_third VARCHAR(20),
    is_progressive BOOLEAN,
    is_final_third_entry BOOLEAN,
    xg NUMERIC(5, 4),
    period INTEGER,
    frame INTEGER,
    duration NUMERIC(10, 2),
    minute INTEGER,
    second INTEGER,
    timestamp VARCHAR(10)
);

